In [41]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Embedding, Input

In [4]:
reviews = [
    'nice food',
    'amazing restaurant',
    'too good',
    'just loved it!',
    'will go again!',
    'horrible food',
    'never go there',
    'poor service', 
    'poor quality',
    'needs improvement'
]

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [21]:
one_hot('amazing_restaurant', 50)

[45, 26]

In [22]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
encoded_reviews

[[29, 28],
 [11, 27],
 [10, 5],
 [7, 15, 7],
 [15, 16, 25],
 [18, 28],
 [24, 16, 12],
 [6, 6],
 [6, 29],
 [21, 23]]

In [23]:
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
padded_reviews

array([[29, 28,  0],
       [11, 27,  0],
       [10,  5,  0],
       [ 7, 15,  7],
       [15, 16, 25],
       [18, 28,  0],
       [24, 16, 12],
       [ 6,  6,  0],
       [ 6, 29,  0],
       [21, 23,  0]], dtype=int32)

In [45]:
embedded_vector_size = 4
model = Sequential()
model.add(Input(shape=(max_length, )))
model.add(Embedding(vocab_size, embedded_vector_size, name='embedding'))
model.add(Flatten())
model.add(Dense(1, activation="sigmoid"))

In [46]:
X = padded_reviews
y = sentiment

In [47]:
model.compile(optimizer='adam',
             loss='binary_crossentropy',
             metrics=['accuracy'])
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 3, 4)           │           120 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_5 (Flatten)             │ (None, 12)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            13 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 133 (532.00 B)

 Trainable params: 133 (532.00 B)

 Non-trainable params: 0 (0.00 B)

In [39]:
model.fit(X,y, epochs=50, verbose=0)

In [28]:
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 1.0000 - loss: 0.6204


1.0

In [29]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [30]:
weights[11]

array([ 0.07431154, -0.01133322,  0.0327378 , -0.01702188], dtype=float32)

In [31]:
weights[29]

array([ 0.02895699, -0.04968596,  0.01424246, -0.00192054], dtype=float32)