In [3]:
import tensorflow_hub as hub
import tensorflow_text as text

In [4]:
preprocess_url = "https://kaggle.com/models/tensorflow/bert/TensorFlow2/en-uncased-preprocess/3"
encoder_url = "https://www.kaggle.com/models/tensorflow/bert/TensorFlow2/en-uncased-l-12-h-768-a-12/4"

In [5]:
# Create function pointer
bert_preprocess_model = hub.KerasLayer(preprocess_url) 

In [6]:
text_test = ['nice movie indeed', 'I love python programming']
text_preprocessed = bert_preprocess_model(text_test)
text_preprocessed.keys()

dict_keys(['input_type_ids', 'input_mask', 'input_word_ids'])

In [7]:
text_preprocessed['input_mask'] # Auto add [CLS] and [SEP] at front and end sentence

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

In [8]:
text_preprocessed['input_type_ids'] # Talk about it later

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

In [10]:
text_preprocessed['input_word_ids'] # Unique ID for the words

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[  101,  3835,  3185,  5262,   102,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

In [11]:
bert_model = hub.KerasLayer(encoder_url)

In [12]:
bert_results = bert_model(text_preprocessed)
bert_results.keys()

dict_keys(['pooled_output', 'sequence_output', 'encoder_outputs', 'default'])

In [14]:
bert_results['pooled_output'] # embedding for entire sentence

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.79177415, -0.21411929,  0.49769533, ...,  0.24465209,
        -0.47334486,  0.8175871 ],
       [-0.917123  , -0.47935176, -0.78656983, ..., -0.6175174 ,
        -0.7102685 ,  0.92184293]], dtype=float32)>

In [15]:
bert_results['sequence_output'] # individual word embedding

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.07292037,  0.08567812,  0.1447685 , ..., -0.09677109,
          0.08722121,  0.07711107],
        [ 0.17839426, -0.19006146,  0.50349414, ..., -0.05869887,
          0.327171  , -0.1557852 ],
        [ 0.18701439, -0.43388805, -0.48875085, ..., -0.15502751,
          0.0014521 , -0.24470903],
        ...,
        [ 0.12083086,  0.12884225,  0.46453533, ...,  0.07375525,
          0.17441948,  0.16522123],
        [ 0.0796792 , -0.01190653,  0.502254  , ...,  0.13777748,
          0.21002203,  0.00624602],
        [-0.07212682, -0.28303498,  0.5903336 , ...,  0.47551885,
          0.16668475, -0.08920328]],

       [[-0.07900576,  0.36335114, -0.21101576, ..., -0.17183727,
          0.16299757,  0.67242616],
        [ 0.27883574,  0.4371623 , -0.357648  , ..., -0.04463609,
          0.38315246,  0.5887981 ],
        [ 1.2037673 ,  1.0727017 ,  0.4840874 , ...,  0.2492101 ,
          0.40730911,  0.40481764],
        ...,

In [18]:
len(bert_results['encoder_outputs']) # 12 encoders --> small bert base, large = 24 encoders

12

In [20]:
bert_results['encoder_outputs'][0]

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.12901425,  0.00644748, -0.03614961, ...,  0.04999627,
          0.06149196, -0.02657561],
        [ 1.1753383 ,  1.214079  ,  1.1569979 , ...,  0.11634393,
         -0.35855335, -0.40490183],
        [ 0.03859039,  0.5386996 , -0.21089831, ...,  0.2185821 ,
          0.72601694, -1.1158606 ],
        ...,
        [-0.07587031, -0.25421914,  0.70755106, ...,  0.5054203 ,
         -0.1887867 ,  0.1502834 ],
        [-0.16066617, -0.28089693,  0.5759709 , ...,  0.5275857 ,
         -0.1114136 ,  0.02887535],
        [-0.0442817 , -0.20279607,  0.59093565, ...,  0.8133836 ,
         -0.390758  , -0.02601741]],

       [[ 0.18903577,  0.02752562, -0.06513738, ..., -0.00620206,
          0.15053889,  0.03165441],
        [ 0.59161466,  0.75891405, -0.07240663, ...,  0.61903954,
          0.82928896,  0.16161957],
        [ 1.4460828 ,  0.44602612,  0.40990272, ...,  0.48255897,
          0.6269115 ,  0.13463409],
        ...,

In [22]:
bert_results['encoder_outputs'][-1] == bert_results["sequence_output"] # last layer of encoder layer == sequeunce output

<tf.Tensor: shape=(2, 128, 768), dtype=bool, numpy=
array([[[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]]])>